### ISSUE TITLE
Notes RE irr_sync.py

### ISSUE THREAD

**Issue by antonalekseev** [vincentbernat/ansible-custom-module-examples#1]
Hi Vincent,

Thanks for the great [write-up](https://vincent.bernat.ch/en/blog/2020-syncing-ripe-arin-apnic-ansible).

Couple of things I've noticed:

This line
https://github.com/vincentbernat/ansible-custom-module-examples/blob/b710cb04efc59ef2e5e08d97fdb8a682502622f6/irr_sync.py#L140
probably meant to be

`proc = subprocess.run(["whois", *args], capture_output=True)`

Also  `whois -h whois.ripe.net -s RIPE -BrG -i mnt-by fr-blade-1-mnt` runs well on Linux, but fails on FreeBSD/macOS. On those systems RIR-specific (query) arguments should be passed as a single argument after a common ones `whois  -h whois.ripe.net -- '-s RIPE -BrG -i mnt-by fr-blade-1-mnt'`.

I understand that you wrote this code for educational purposes and it wasn't meant to be nor production-ready neither portable, just a note FYI.

**Comment by vincentbernat** [comment]
Thanks for the fix! I have fixed both the module and the article.

For the whois syntax, I have fixed the article as people are more likely to run the whois examples from their workstation as they read the article. I will leave the invocation as is in the module by lazyness.

The module is derived from the one we use in production and is intended to be ready to use, so fixing it is important. Ansible execution environment reproducibility is a big problem and we solve it by wrapping it inside Docker, so we know everyone is using the same Python version, the same modules and the same whois executable.

**Comment by antonalekseev** [comment]
One more minor point. `gpg` (at least versions I have on hand `gpg (GnuPG/MacGPG2) 2.2.20`, `gpg (GnuPG) 2.2.19`) doesn't have `--user` argument.

https://github.com/vincentbernat/vincent.bernat.ch/blob/210a28240946631c1747417c560526b9fe9123a2/content/en/blog/2020-syncing-ripe-arin-apnic-ansible.html#L110

It's either `-u` or `--local-user`
```
 -u, --local-user USER-ID    use USER-ID to sign or decrypt
```
Worse still, in the case of `--user` supplied `gpg` doesn't issue a warning on the matter and silently uses default identity.

**Comment by vincentbernat** [comment]
Thanks!

Looking at the source code, --user is an alias for --recipient, which is useless when signing.
